# Generated by Django 3.0.5 on 2020-04-13 00:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailtrans', '0009_create_initial_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
                ('body', wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('in_navigation', wagtail.core.blocks.CharBlock(help_text='Fill if you want this section added in page navigation', required=False)), ('headline', wagtail.core.blocks.CharBlock()), ('lead', wagtail.core.blocks.CharBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock()), ('hero_image', wagtail.images.blocks.ImageChooserBlock(required=False))], icon='image')), ('content_section', wagtail.core.blocks.StructBlock([('in_navigation', wagtail.core.blocks.CharBlock(help_text='Fill if you want this section added in page navigation', required=False)), ('content', wagtail.core.blocks.RichTextBlock()), ('section_image', wagtail.images.blocks.ImageChooserBlock(required=False))], icon='doc-full-inverse')), ('features_list', wagtail.core.blocks.StructBlock([('in_navigation', wagtail.core.blocks.CharBlock(help_text='Fill if you want this section added in page navigation', required=False)), ('headline', wagtail.core.blocks.CharBlock()), ('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock())], icon='doc-full-inverse'), icon='table'))]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage',),
        ),
    ]
